remove container run

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -55,25 +55,25 @@ jobs:
       # - name: List cached Docker layers
       #   run: ls -l /tmp/.buildx-cache
         
-      - name: Run Docker container
-        id: run-gazebo
-        run: |
-          docker run --name gazebo_container ardupilot_gazebo &
-          CONTAINER_ID=$(docker ps -qf "name=gazebo_container")
-          sleep 30  # Adjust the sleep duration as needed for the simulation to complete
-          docker logs $CONTAINER_ID
-          if docker wait $CONTAINER_ID | grep -q "0"; then
-            echo "Simulation succeeded."
-            docker stop $CONTAINER_ID
-            docker rm $CONTAINER_ID
-            echo "success" > result.txt
-          else
-            echo "Simulation failed."
-            docker stop $CONTAINER_ID
-            docker rm $CONTAINER_ID
-            echo "failure" > result.txt
-            exit 1
-          fi
+      # - name: Run Docker container
+      #   id: run-gazebo
+      #   run: |
+      #     docker run --name gazebo_container ardupilot_gazebo &
+      #     CONTAINER_ID=$(docker ps -qf "name=gazebo_container")
+      #     sleep 30  # Adjust the sleep duration as needed for the simulation to complete
+      #     docker logs $CONTAINER_ID
+      #     if docker wait $CONTAINER_ID | grep -q "0"; then
+      #       echo "Simulation succeeded."
+      #       docker stop $CONTAINER_ID
+      #       docker rm $CONTAINER_ID
+      #       echo "success" > result.txt
+      #     else
+      #       echo "Simulation failed."
+      #       docker stop $CONTAINER_ID
+      #       docker rm $CONTAINER_ID
+      #       echo "failure" > result.txt
+      #       exit 1
+      #     fi
 
 
 
